name: Cypress integration and E2E tests

on: [pull_request]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        environment: Dev
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependecies
              run: npm install

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
                  headless: true
                  record: false
                  start: npm start
                  wait-on: http://localhost:3000
              env:
                  REACT_APP_ENV: dev
                  REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
                  REACT_APP_GA_TRACKING_ID: ${{ secrets.GA_MEASUREMENT_ID }}
                  REACT_APP_MAP_THEME_URL: mapbox://styles/healthmap/cknr3ycvx03i917nw4gk1um66

                  REACT_APP_COUNTRY_VIEW_DATA_URL: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/country/latest.json
                  REACT_APP_TOTAL_CASES_URL: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/total/latest.json
                  REACT_APP_POLICY_PUBLIC_ID: 89575059
                  REACT_APP_COOKIE_CONSENT_PUBLIC_ID: 2070778
