name: Cypress integration and E2E tests

on: [pull_request]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        environment: Dev
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependecies
              run: npm install

              # ! This step should be commencted when pushing to github !
            # - name: Install Cypress dependencies (local only!)
            #   run: |
            #       apt-get update
            #       apt-get --assume-yes install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                  browser: electron
                  record: false
                  start: npm start
                  wait-on: http://localhost:3000
              env:
                  REACT_APP_ENV: dev
                  REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
                  REACT_APP_GA_TRACKING_ID: ${{ secrets.GA_MEASUREMENT_ID }}
                  REACT_APP_MAP_THEME_URL: mapbox://styles/healthmap/cknr3ycvx03i917nw4gk1um66
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

                  REACT_APP_COUNTRY_VIEW_DATA_URL: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/country/latest.json
                  REACT_APP_TOTAL_CASES_URL: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/total/latest.json
                  REACT_APP_TIMESERIES_COUNTRY_DATA: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/timeseries/country_confirmed.json
                  REACT_APP_TIMESERIES_COUNT_DATA: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/timeseries/confirmed.json
                  REACT_APP_POLICY_PUBLIC_ID: 89575059
                  REACT_APP_COOKIE_CONSENT_PUBLIC_ID: 2070778
