name: Cypress integration and E2E tests

on: [pull_request]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        environment: Dev
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependecies
              run: npm install

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
                  headless: true
                  record: true
                  start: npm start
                  wait-on: http://localhost:3000
              env:
                  REACT_APP_ENV: dev
                  REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
                  REACT_APP_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
                  CYPRESS_RECORD_KEY: ce3ef329-58af-44a3-83d7-acbf381e3646
                  REACT_APP_MAP_THEME_URL: mapbox://styles/healthmap/cknr3ycvx03i917nw4gk1um66
                  REACT_APP_SHEETS_ID: 15-2lbrYHHL0zFYc9kzS7_m6CCV5BkBCUeg9ifTHbRos
                  REACT_APP_SHEET_NAME: Variants
                  REACT_APP_DATA_PORTAL_URL: https://dev-data.covid-19.global.health
                  REACT_APP_COUNTRY_VIEW_DATA_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/country/latest.json
                  REACT_APP_VARIANT_DATA_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/variant-reporting-data.json
                  REACT_APP_REGIONAL_VIEW_DATA_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/regional/latest.json
                  REACT_APP_TOTAL_CASES_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/total/latest.json
                  REACT_APP_COMPLETENESS_DATA_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/metrics/completeness.json
                  REACT_APP_FRESHNESS_DATA_URL: https://covid-19-aggregates-dev.s3.eu-central-1.amazonaws.com/metrics/freshness.json
