name: Build and deploy - QA

on:
    push:
        branches:
            - test

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Test
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependecies
              run: npm install

            - name: Create qa build
              run: npm run build
              env:
                  REACT_APP_ENV: qa
                  REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
                  REACT_APP_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
                  REACT_APP_GA_TRACKING_ID: ''
                  REACT_APP_MAP_THEME_URL: mapbox://styles/healthmap/cknr3ycvx03i917nw4gk1um66
                  REACT_APP_SHEETS_ID: 15-2lbrYHHL0zFYc9kzS7_m6CCV5BkBCUeg9ifTHbRos
                  REACT_APP_SHEET_NAME: Variants
                  REACT_APP_DATA_PORTAL_URL: https://data.covid-19.global.health
                  REACT_APP_COUNTRY_VIEW_DATA_URL: https://covid-19-aggregates.s3.amazonaws.com/country/latest.json
                  REACT_APP_VARIANT_DATA_URL: https://covid-19-aggregates.s3.amazonaws.com/variant-reporting-data.json
                  REACT_APP_REGIONAL_VIEW_DATA_URL: https://covid-19-aggregates.s3.amazonaws.com/regional/latest.json
                  REACT_APP_TOTAL_CASES_URL: https://covid-19-aggregates.s3.amazonaws.com/total/latest.json
                  REACT_APP_COMPLETENESS_DATA_URL: https://covid-19-aggregates.s3.amazonaws.com/metrics/completeness.json
                  REACT_APP_FRESHNESS_DATA_URL: https://covid-19-aggregates.s3.amazonaws.com/metrics/freshness.json
                  REACT_APP_POLICY_PUBLIC_ID: 89575059
                  REACT_APP_COOKIE_CONSENT_PUBLIC_ID: 2070778

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Deploy to AWS S3
              run: aws s3 sync ./build s3://eu-qa-map.covid-19.global.health --delete
