name: Build and deploy - PROD

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Prod
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependecies
              run: npm install

            - name: Create production build
              run: npm run build
              env:
                  REACT_APP_ENV: prod
                  REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
                  REACT_APP_GA_TRACKING_ID: ${{ secrets.GA_MEASUREMENT_ID }}
                  REACT_APP_MAP_THEME_URL: mapbox://styles/healthmap/cknr3ycvx03i917nw4gk1um66

                  REACT_APP_COUNTRY_VIEW_DATA_URL: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/country-who/latest.json
                  REACT_APP_TOTAL_CASES_URL: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/total-who/latest.json
                  REACT_APP_TIMESERIES_COUNTRY_DATA: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/timeseries-who/country_confirmed.json
                  REACT_APP_TIMESERIES_COUNT_DATA: https://monkeypox-aggregates.s3.eu-central-1.amazonaws.com/timeseries-who/confirmed.json
                  REACT_APP_POLICY_PUBLIC_ID: 89575059
                  REACT_APP_COOKIE_CONSENT_PUBLIC_ID: 2070778

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Deploy to AWS S3
              run: aws s3 sync ./build s3://map.monkeypox.global.health --delete
